using SylviaNG.Recruitment.Application.Features.JobPostings.Models;
using SylviaNG.Recruitment.Domain.Entities;
using SylviaNG.Recruitment.Domain.Enums;

namespace SylviaNG.Recruitment.Application.Mappings
{
    /// <summary>
    /// Manual mapping methods for JobPosting and JobApplication entities.
    /// Follow this pattern for all new feature mappings.
    /// </summary>
    public static class JobPostingMapper
    {
        // ── JobPosting Mappings ──────────────────────────────────────────

        public static JobPosting ToEntity(this JobPostingCreateRequest request)
        {
            // Note: JobPostingCode is intentionally NOT set here - it is generated by
            // JobPostingService.CreateAsync once the entity has its identity (JobPostingId).
            return new JobPosting
            {
                SiteId = request.SiteId,
                DepartmentId = request.DepartmentId,
                DesignationId = request.DesignationId,
                Title = request.Title,
                Description = request.Description,
                Requirements = request.Requirements,
                NumberOfPositions = request.NumberOfPositions,
                EmploymentType = request.EmploymentType,
                MinSalary = request.MinSalary,
                MaxSalary = request.MaxSalary,
                PostingDate = request.PostingDate,
                ClosingDate = request.ClosingDate,
                IsActive = true,
                Location = request.Location,
                CircularType = request.CircularType,
                MinAge = request.MinAge,
                MaxAge = request.MaxAge,
                MinEducationLevel = request.MinEducationLevel,
                MinExperienceYears = request.MinExperienceYears,
                RequiredDistrict = request.RequiredDistrict,
                ApplicationFeeAmount = request.ApplicationFeeAmount,
                ApplicationFeeCurrency = request.ApplicationFeeCurrency,
                HiringPipelineId = request.HiringPipelineId,
                AssessmentWorkflowId = request.AssessmentWorkflowId
            };
        }

        public static void ApplyUpdate(this JobPosting entity, JobPostingUpdateRequest request)
        {
            if (request.DepartmentId.HasValue) entity.DepartmentId = request.DepartmentId;
            if (request.DesignationId.HasValue) entity.DesignationId = request.DesignationId;
            if (request.Title != null) entity.Title = request.Title;
            if (request.Description != null) entity.Description = request.Description;
            if (request.Requirements != null) entity.Requirements = request.Requirements;
            if (request.NumberOfPositions.HasValue) entity.NumberOfPositions = request.NumberOfPositions.Value;
            if (request.EmploymentType.HasValue) entity.EmploymentType = request.EmploymentType.Value;
            if (request.Status.HasValue) entity.Status = request.Status.Value;
            if (request.MinSalary.HasValue) entity.MinSalary = request.MinSalary;
            if (request.MaxSalary.HasValue) entity.MaxSalary = request.MaxSalary;
            if (request.PostingDate.HasValue) entity.PostingDate = request.PostingDate;
            if (request.ClosingDate.HasValue) entity.ClosingDate = request.ClosingDate;
            if (request.IsActive.HasValue) entity.IsActive = request.IsActive.Value;
            if (request.Location != null) entity.Location = request.Location;
            if (request.CircularType.HasValue) entity.CircularType = request.CircularType.Value;
            if (request.MinAge.HasValue) entity.MinAge = request.MinAge;
            if (request.MaxAge.HasValue) entity.MaxAge = request.MaxAge;
            if (request.MinEducationLevel.HasValue) entity.MinEducationLevel = request.MinEducationLevel;
            if (request.MinExperienceYears.HasValue) entity.MinExperienceYears = request.MinExperienceYears;
            if (request.RequiredDistrict != null) entity.RequiredDistrict = request.RequiredDistrict;
            if (request.ApplicationFeeAmount.HasValue) entity.ApplicationFeeAmount = request.ApplicationFeeAmount;
            if (request.ApplicationFeeCurrency != null) entity.ApplicationFeeCurrency = request.ApplicationFeeCurrency;
            if (request.HiringPipelineId.HasValue) entity.HiringPipelineId = request.HiringPipelineId;
            if (request.AssessmentWorkflowId.HasValue) entity.AssessmentWorkflowId = request.AssessmentWorkflowId;
        }

        public static JobPostingResponse ToResponse(this JobPosting entity)
        {
            return new JobPostingResponse
            {
                JobPostingId = entity.JobPostingId,
                JobPostingCode = entity.JobPostingCode,
                SiteId = entity.SiteId,
                DepartmentId = entity.DepartmentId,
                DesignationId = entity.DesignationId,
                Title = entity.Title,
                Description = entity.Description,
                Requirements = entity.Requirements,
                NumberOfPositions = entity.NumberOfPositions,
                EmploymentType = entity.EmploymentType,
                Status = entity.Status,
                MinSalary = entity.MinSalary,
                MaxSalary = entity.MaxSalary,
                PostingDate = entity.PostingDate,
                ClosingDate = entity.ClosingDate,
                IsActive = entity.IsActive,
                TotalApplications = entity.Applications?.Count ?? 0,
                Location = entity.Location,
                CircularType = entity.CircularType,
                MinAge = entity.MinAge,
                MaxAge = entity.MaxAge,
                MinEducationLevel = entity.MinEducationLevel,
                MinExperienceYears = entity.MinExperienceYears,
                RequiredDistrict = entity.RequiredDistrict,
                ApplicationFeeAmount = entity.ApplicationFeeAmount,
                ApplicationFeeCurrency = entity.ApplicationFeeCurrency,
                HiringPipelineId = entity.HiringPipelineId,
                HiringPipelineName = entity.HiringPipeline?.Name,
                AssessmentWorkflowId = entity.AssessmentWorkflowId,
                AssessmentWorkflowName = entity.AssessmentWorkflow?.Name
            };
        }

        public static JobPostingLookupResponse ToLookupResponse(this JobPosting entity)
        {
            return new JobPostingLookupResponse
            {
                JobPostingId = entity.JobPostingId,
                Title = entity.Title
            };
        }

        // ── JobApplication Mappings ──────────────────────────────────────

        public static JobApplication ToEntity(this JobApplicationCreateRequest request)
        {
            return new JobApplication
            {
                JobPostingId = request.JobPostingId,
                CandidateName = request.CandidateName,
                CandidateEmail = request.CandidateEmail,
                CandidatePhone = request.CandidatePhone,
                CandidateNationalId = request.CandidateNationalId,
                ResumeUrl = request.ResumeUrl,
                CoverLetter = request.CoverLetter,
                IsActive = true
            };
        }

        public static void ApplyUpdate(this JobApplication entity, JobApplicationUpdateRequest request)
        {
            if (request.ApplicationStatus.HasValue) entity.ApplicationStatus = request.ApplicationStatus.Value;
            if (request.CandidatePhone != null) entity.CandidatePhone = request.CandidatePhone;
            if (request.ResumeUrl != null) entity.ResumeUrl = request.ResumeUrl;
            if (request.CoverLetter != null) entity.CoverLetter = request.CoverLetter;
            if (request.IsActive.HasValue) entity.IsActive = request.IsActive.Value;
        }

        public static JobApplicationResponse ToResponse(this JobApplication entity)
        {
            return new JobApplicationResponse
            {
                JobApplicationId = entity.JobApplicationId,
                JobPostingId = entity.JobPostingId,
                JobPostingTitle = entity.JobPosting?.Title,
                CandidateName = entity.CandidateName,
                CandidateEmail = entity.CandidateEmail,
                CandidatePhone = entity.CandidatePhone,
                ResumeUrl = entity.ResumeUrl,
                ApplicationStatus = entity.ApplicationStatus,
                AppliedDate = entity.AppliedDate,
                IsActive = entity.IsActive,
                Source = entity.Source,
                PaymentRequired = entity.ApplicationStatus == ApplicationStatusEnum.AwaitingPayment
            };
        }

        // ── ATS Dashboard / Status History Mappings (US-035/US-036) ───────

        public static JobApplicationDashboardResponse ToDashboardResponse(this JobApplication entity)
        {
            return new JobApplicationDashboardResponse
            {
                JobApplicationId = entity.JobApplicationId,
                CandidateName = entity.CandidateName,
                JobPostingId = entity.JobPostingId,
                JobPostingTitle = entity.JobPosting?.Title,
                Source = entity.Source,
                AppliedDate = entity.AppliedDate,
                ApplicationStatus = entity.ApplicationStatus
            };
        }

        public static JobApplicationDetailResponse ToDetailResponse(this JobApplication entity)
        {
            return new JobApplicationDetailResponse
            {
                JobApplicationId = entity.JobApplicationId,
                JobPostingId = entity.JobPostingId,
                JobPostingTitle = entity.JobPosting?.Title,
                CandidateName = entity.CandidateName,
                CandidateEmail = entity.CandidateEmail,
                CandidatePhone = entity.CandidatePhone,
                ResumeUrl = entity.ResumeUrl,
                CoverLetter = entity.CoverLetter,
                ApplicationStatus = entity.ApplicationStatus,
                AppliedDate = entity.AppliedDate,
                Source = entity.Source,
                StatusHistory = entity.StatusHistory.Select(h => h.ToResponse()).ToList()
            };
        }

        // ── Candidate Self-Service (US-040) ────────────────────────────────

        public static MyApplicationResponse ToMyApplicationResponse(this JobApplication entity, bool canWithdraw)
        {
            return new MyApplicationResponse
            {
                JobApplicationId = entity.JobApplicationId,
                JobPostingId = entity.JobPostingId,
                JobPostingTitle = entity.JobPosting?.Title,
                AppliedDate = entity.AppliedDate,
                ApplicationStatus = entity.ApplicationStatus,
                CanWithdraw = canWithdraw,
                Interviews = entity.Interviews
                    .Where(i => i.IsActive)
                    .OrderBy(i => i.ScheduledDate)
                    .Select(i => i.ToMyApplicationInterviewResponse())
                    .ToList()
            };
        }

        public static MyApplicationInterviewResponse ToMyApplicationInterviewResponse(this Interview entity)
        {
            return new MyApplicationInterviewResponse
            {
                InterviewId = entity.InterviewId,
                ScheduledDate = entity.ScheduledDate,
                Location = entity.Location,
                MeetingLink = entity.MeetingLink,
                Round = entity.Round
            };
        }

        public static ApplicationStatusHistoryResponse ToResponse(this ApplicationStatusHistory entity)
        {
            return new ApplicationStatusHistoryResponse
            {
                ApplicationStatusHistoryId = entity.ApplicationStatusHistoryId,
                FromStatus = entity.FromStatus,
                ToStatus = entity.ToStatus,
                ChangedByUserName = entity.ChangedByUserName,
                ChangedAt = entity.ChangedAt,
                ReasonId = entity.ReasonId,
                ReasonLabel = entity.Reason?.Label,
                Note = entity.Note
            };
        }

        public static ApplicationStatusReasonResponse ToResponse(this ApplicationStatusReason entity)
        {
            return new ApplicationStatusReasonResponse
            {
                ApplicationStatusReasonId = entity.ApplicationStatusReasonId,
                Label = entity.Label,
                AppliesToStatus = entity.AppliesToStatus,
                DisplayOrder = entity.DisplayOrder
            };
        }

        // ── Career Portal / Internal Job Board apply mapping ──────────────

        public static JobApplication ToEntity(this JobApplicationSubmitRequest request)
        {
            // ResumeUrl, Source, ApplicationStatus and AppliedDate are set by
            // JobApplicationService.SubmitAsync once the CV (if any) has been saved.
            return new JobApplication
            {
                JobPostingId = request.JobPostingId,
                CandidateName = request.CandidateName,
                CandidateEmail = request.CandidateEmail,
                CandidatePhone = request.CandidatePhone,
                CandidateNationalId = request.CandidateNationalId,
                CoverLetter = request.CoverLetter,
                IsActive = true
            };
        }

        // ── Duplicate Detection (US-038) ──────────────────────────────────

        public static JobApplicationDuplicateItemResponse ToDuplicateItemResponse(this JobApplication entity)
        {
            return new JobApplicationDuplicateItemResponse
            {
                JobApplicationId = entity.JobApplicationId,
                CandidateName = entity.CandidateName,
                CandidateEmail = entity.CandidateEmail,
                CandidatePhone = entity.CandidatePhone,
                CandidateNationalId = entity.CandidateNationalId,
                Source = entity.Source,
                ApplicationStatus = entity.ApplicationStatus,
                AppliedDate = entity.AppliedDate,
                ResumeUrl = entity.ResumeUrl
            };
        }
    }
}
