// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SylviaNG.Recruitment.Infrastructure.Data;

#nullable disable

namespace SylviaNG.Recruitment.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260709060323_AddHiringPipeline")]
    partial class AddHiringPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EmployeeId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DesignatioId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("RFId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<long?>("SiteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeCode");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.HiringPipeline", b =>
                {
                    b.Property<long>("HiringPipelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HiringPipelineId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("HiringPipelineId");

                    b.HasIndex("Name");

                    b.ToTable("HiringPipelines", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.Interview", b =>
                {
                    b.Property<long>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InterviewId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<long?>("InterviewerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("JobApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Round")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("InterviewId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("Interviews", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobApplication", b =>
                {
                    b.Property<long>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobApplicationId"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CandidateEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidatePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("External");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("CandidateEmail", "JobPostingId")
                        .IsUnique();

                    b.ToTable("JobApplications", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobPosting", b =>
                {
                    b.Property<long>("JobPostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobPostingId"));

                    b.Property<decimal?>("ApplicationFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationFeeCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CircularType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("DesignationId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("HiringPipelineId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobPostingCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer");

                    b.Property<string>("MinEducationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("MinExperienceYears")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfPositions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("PostingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("RequiredDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("JobPostingId");

                    b.HasIndex("HiringPipelineId");

                    b.HasIndex("JobPostingCode")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.HasIndex("Status");

                    b.HasIndex("SiteId", "Title")
                        .IsUnique();

                    b.ToTable("JobPostings", (string)null);

                    b.HasData(
                        new
                        {
                            JobPostingId = 1L,
                            CircularType = "Both",
                            ClosingDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1L,
                            DepartmentId = 1L,
                            Description = "We are looking for a Senior Software Engineer to join our team.",
                            DesignationId = 1L,
                            EmploymentType = "FullTime",
                            IsActive = true,
                            JobPostingCode = "JOB-2026-000001",
                            MaxSalary = 120000m,
                            MinSalary = 80000m,
                            NumberOfPositions = 2,
                            PostingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "5+ years of experience in .NET, C#, and SQL Server.",
                            SiteId = 1L,
                            Status = "Open",
                            TenantId = "default_tenant",
                            Title = "Senior Software Engineer"
                        },
                        new
                        {
                            JobPostingId = 2L,
                            CircularType = "Both",
                            ClosingDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1L,
                            DepartmentId = 2L,
                            Description = "Looking for a creative UI/UX Designer.",
                            DesignationId = 2L,
                            EmploymentType = "FullTime",
                            IsActive = true,
                            JobPostingCode = "JOB-2026-000002",
                            MaxSalary = 80000m,
                            MinSalary = 50000m,
                            NumberOfPositions = 1,
                            PostingDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Requirements = "3+ years of experience in Figma and Adobe XD.",
                            SiteId = 1L,
                            Status = "Open",
                            TenantId = "default_tenant",
                            Title = "UI/UX Designer"
                        });
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobPostingAttachment", b =>
                {
                    b.Property<long>("JobPostingAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JobPostingAttachmentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("JobPostingAttachmentId");

                    b.HasIndex("JobPostingId");

                    b.ToTable("JobPostingAttachments", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.PipelineStage", b =>
                {
                    b.Property<long>("PipelineStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PipelineStageId"));

                    b.Property<bool>("AllowCandidateReschedule")
                        .HasColumnType("boolean");

                    b.Property<string>("AutoProgressionRule")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ColorBadge")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EmailTemplate")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<long>("HiringPipelineId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManualApprovalRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotifyCandidateOnEnter")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyInterviewersOnAssign")
                        .HasColumnType("boolean");

                    b.Property<string>("PassingCriteria")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("RequiredDocuments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("SlaDays")
                        .HasColumnType("integer");

                    b.Property<string>("StageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("PipelineStageId");

                    b.HasIndex("HiringPipelineId", "DisplayOrder");

                    b.ToTable("PipelineStages", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.PipelineStageInterviewer", b =>
                {
                    b.Property<long>("PipelineStageId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.HasKey("PipelineStageId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PipelineStageInterviewers", (string)null);
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.Interview", b =>
                {
                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany("Interviews")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.HiringPipeline", "HiringPipeline")
                        .WithMany("JobPostings")
                        .HasForeignKey("HiringPipelineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HiringPipeline");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobPostingAttachment", b =>
                {
                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Attachments")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.PipelineStage", b =>
                {
                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.HiringPipeline", "HiringPipeline")
                        .WithMany("Stages")
                        .HasForeignKey("HiringPipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HiringPipeline");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.PipelineStageInterviewer", b =>
                {
                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SylviaNG.Recruitment.Domain.Entities.PipelineStage", "PipelineStage")
                        .WithMany("Interviewers")
                        .HasForeignKey("PipelineStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PipelineStage");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.HiringPipeline", b =>
                {
                    b.Navigation("JobPostings");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SylviaNG.Recruitment.Domain.Entities.PipelineStage", b =>
                {
                    b.Navigation("Interviewers");
                });
#pragma warning restore 612, 618
        }
    }
}
