using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SylviaNG.Recruitment.Domain.Entities;

namespace SylviaNG.Recruitment.Infrastructure.Configurations
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        private static readonly DateTime SeedCreatedAt = new(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        // Bangladesh seeded first (id 1) so it's the default selection for the country-code
        // dropdown - most candidates are local. Rest of the list is standard ISO alpha-2 +
        // international dial code, not exhaustive of every territory. Admin/HR can add/edit/
        // delete freely afterward.
        private static readonly (string Name, string Code, string DialCode)[] Countries =
        {
            ("Bangladesh", "BD", "+880"),
            ("India", "IN", "+91"),
            ("Pakistan", "PK", "+92"),
            ("Sri Lanka", "LK", "+94"),
            ("Nepal", "NP", "+977"),
            ("Bhutan", "BT", "+975"),
            ("Myanmar", "MM", "+95"),
            ("Afghanistan", "AF", "+93"),
            ("Maldives", "MV", "+960"),
            ("China", "CN", "+86"),
            ("Japan", "JP", "+81"),
            ("South Korea", "KR", "+82"),
            ("North Korea", "KP", "+850"),
            ("Mongolia", "MN", "+976"),
            ("Taiwan", "TW", "+886"),
            ("Hong Kong", "HK", "+852"),
            ("Macau", "MO", "+853"),
            ("Vietnam", "VN", "+84"),
            ("Thailand", "TH", "+66"),
            ("Cambodia", "KH", "+855"),
            ("Laos", "LA", "+856"),
            ("Malaysia", "MY", "+60"),
            ("Singapore", "SG", "+65"),
            ("Indonesia", "ID", "+62"),
            ("Philippines", "PH", "+63"),
            ("Brunei", "BN", "+673"),
            ("Timor-Leste", "TL", "+670"),
            ("Saudi Arabia", "SA", "+966"),
            ("United Arab Emirates", "AE", "+971"),
            ("Qatar", "QA", "+974"),
            ("Kuwait", "KW", "+965"),
            ("Bahrain", "BH", "+973"),
            ("Oman", "OM", "+968"),
            ("Yemen", "YE", "+967"),
            ("Iraq", "IQ", "+964"),
            ("Iran", "IR", "+98"),
            ("Israel", "IL", "+972"),
            ("Palestine", "PS", "+970"),
            ("Jordan", "JO", "+962"),
            ("Lebanon", "LB", "+961"),
            ("Syria", "SY", "+963"),
            ("Turkey", "TR", "+90"),
            ("Cyprus", "CY", "+357"),
            ("Kazakhstan", "KZ", "+7"),
            ("Uzbekistan", "UZ", "+998"),
            ("Turkmenistan", "TM", "+993"),
            ("Tajikistan", "TJ", "+992"),
            ("Kyrgyzstan", "KG", "+996"),
            ("Azerbaijan", "AZ", "+994"),
            ("Armenia", "AM", "+374"),
            ("Georgia", "GE", "+995"),
            ("Russia", "RU", "+7"),
            ("Ukraine", "UA", "+380"),
            ("Belarus", "BY", "+375"),
            ("Moldova", "MD", "+373"),
            ("Poland", "PL", "+48"),
            ("Czech Republic", "CZ", "+420"),
            ("Slovakia", "SK", "+421"),
            ("Hungary", "HU", "+36"),
            ("Romania", "RO", "+40"),
            ("Bulgaria", "BG", "+359"),
            ("Serbia", "RS", "+381"),
            ("Croatia", "HR", "+385"),
            ("Slovenia", "SI", "+386"),
            ("Bosnia and Herzegovina", "BA", "+387"),
            ("Montenegro", "ME", "+382"),
            ("North Macedonia", "MK", "+389"),
            ("Albania", "AL", "+355"),
            ("Kosovo", "XK", "+383"),
            ("Greece", "GR", "+30"),
            ("Italy", "IT", "+39"),
            ("Malta", "MT", "+356"),
            ("Vatican City", "VA", "+379"),
            ("San Marino", "SM", "+378"),
            ("Spain", "ES", "+34"),
            ("Portugal", "PT", "+351"),
            ("Andorra", "AD", "+376"),
            ("France", "FR", "+33"),
            ("Monaco", "MC", "+377"),
            ("Germany", "DE", "+49"),
            ("Austria", "AT", "+43"),
            ("Switzerland", "CH", "+41"),
            ("Liechtenstein", "LI", "+423"),
            ("Belgium", "BE", "+32"),
            ("Netherlands", "NL", "+31"),
            ("Luxembourg", "LU", "+352"),
            ("United Kingdom", "GB", "+44"),
            ("Ireland", "IE", "+353"),
            ("Iceland", "IS", "+354"),
            ("Denmark", "DK", "+45"),
            ("Norway", "NO", "+47"),
            ("Sweden", "SE", "+46"),
            ("Finland", "FI", "+358"),
            ("Estonia", "EE", "+372"),
            ("Latvia", "LV", "+371"),
            ("Lithuania", "LT", "+370"),
            ("United States", "US", "+1"),
            ("Canada", "CA", "+1"),
            ("Mexico", "MX", "+52"),
            ("Guatemala", "GT", "+502"),
            ("Belize", "BZ", "+501"),
            ("El Salvador", "SV", "+503"),
            ("Honduras", "HN", "+504"),
            ("Nicaragua", "NI", "+505"),
            ("Costa Rica", "CR", "+506"),
            ("Panama", "PA", "+507"),
            ("Cuba", "CU", "+53"),
            ("Jamaica", "JM", "+1876"),
            ("Haiti", "HT", "+509"),
            ("Dominican Republic", "DO", "+1809"),
            ("Trinidad and Tobago", "TT", "+1868"),
            ("Bahamas", "BS", "+1242"),
            ("Barbados", "BB", "+1246"),
            ("Brazil", "BR", "+55"),
            ("Argentina", "AR", "+54"),
            ("Chile", "CL", "+56"),
            ("Peru", "PE", "+51"),
            ("Colombia", "CO", "+57"),
            ("Venezuela", "VE", "+58"),
            ("Ecuador", "EC", "+593"),
            ("Bolivia", "BO", "+591"),
            ("Paraguay", "PY", "+595"),
            ("Uruguay", "UY", "+598"),
            ("Guyana", "GY", "+592"),
            ("Suriname", "SR", "+597"),
            ("Egypt", "EG", "+20"),
            ("Libya", "LY", "+218"),
            ("Tunisia", "TN", "+216"),
            ("Algeria", "DZ", "+213"),
            ("Morocco", "MA", "+212"),
            ("Sudan", "SD", "+249"),
            ("South Sudan", "SS", "+211"),
            ("Ethiopia", "ET", "+251"),
            ("Eritrea", "ER", "+291"),
            ("Djibouti", "DJ", "+253"),
            ("Somalia", "SO", "+252"),
            ("Kenya", "KE", "+254"),
            ("Uganda", "UG", "+256"),
            ("Tanzania", "TZ", "+255"),
            ("Rwanda", "RW", "+250"),
            ("Burundi", "BI", "+257"),
            ("Nigeria", "NG", "+234"),
            ("Ghana", "GH", "+233"),
            ("Ivory Coast", "CI", "+225"),
            ("Senegal", "SN", "+221"),
            ("Mali", "ML", "+223"),
            ("Niger", "NE", "+227"),
            ("Chad", "TD", "+235"),
            ("Cameroon", "CM", "+237"),
            ("Gabon", "GA", "+241"),
            ("Congo", "CG", "+242"),
            ("DR Congo", "CD", "+243"),
            ("Angola", "AO", "+244"),
            ("Zambia", "ZM", "+260"),
            ("Zimbabwe", "ZW", "+263"),
            ("Malawi", "MW", "+265"),
            ("Mozambique", "MZ", "+258"),
            ("Namibia", "NA", "+264"),
            ("Botswana", "BW", "+267"),
            ("South Africa", "ZA", "+27"),
            ("Lesotho", "LS", "+266"),
            ("Eswatini", "SZ", "+268"),
            ("Madagascar", "MG", "+261"),
            ("Mauritius", "MU", "+230"),
            ("Seychelles", "SC", "+248"),
            ("Australia", "AU", "+61"),
            ("New Zealand", "NZ", "+64"),
            ("Fiji", "FJ", "+679"),
            ("Papua New Guinea", "PG", "+675"),
        };

        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.ToTable("Countries");
            builder.HasKey(c => c.CountryId);

            builder.Property(c => c.Name).IsRequired().HasMaxLength(100);
            builder.Property(c => c.Code).IsRequired().HasMaxLength(5);
            builder.Property(c => c.DialCode).IsRequired().HasMaxLength(10);
            builder.HasIndex(c => c.Name).IsUnique();
            builder.HasIndex(c => c.Code).IsUnique();

            builder.HasData(Countries.Select((c, index) => new
            {
                CountryId = (long)(index + 1),
                c.Name,
                c.Code,
                c.DialCode,
                TenantId = "default_tenant",
                Remarks = (string?)null,
                CreatedAt = SeedCreatedAt,
                CreatedBy = 1L,
                UpdatedAt = (DateTime?)null,
                UpdatedBy = (long?)null,
                DeletedAt = (DateTime?)null,
                DeletedBy = (long?)null,
                Status = 1
            }));
        }
    }
}
