using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SylviaNG.Recruitment.Application.Interfaces.Services;
using SylviaNG.Recruitment.Domain.Entities;

namespace SylviaNG.Recruitment.Infrastructure.Documents
{
    /// <summary>
    /// Renders the full seat plan for an exam, grouped by room (US-056). Same QuestPDF
    /// Document.Create / Compose* / Header-Content-Footer shape as QuestPdfCvGenerator.
    /// </summary>
    public class QuestPdfSeatPlanGenerator : ISeatPlanPdfGeneratorService
    {
        public byte[] Generate(Exam exam, List<ExamEnrollment> enrollments)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(36);
                    page.DefaultTextStyle(x => x.FontSize(10).FontColor(Colors.Grey.Darken3));

                    page.Header().Element(header => ComposeHeader(header, exam));
                    page.Content().PaddingTop(15).Element(content => ComposeContent(content, enrollments));

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by SylviaNG Recruitment - Page ").FontSize(8);
                        x.CurrentPageNumber().FontSize(8);
                        x.Span(" of ").FontSize(8);
                        x.TotalPages().FontSize(8);
                    });
                });
            });

            return document.GeneratePdf();
        }

        private static void ComposeHeader(IContainer container, Exam exam)
        {
            container.Column(column =>
            {
                column.Item().Text(exam.Title).FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                column.Item().Text("Exam Seat Plan").FontSize(11).Italic().FontColor(Colors.Grey.Medium);

                column.Item().PaddingTop(8).Text(text =>
                {
                    text.Span("Scheduled: ").SemiBold();
                    text.Span($"{exam.ScheduledStartAt:dddd, dd MMM yyyy HH:mm} ({exam.DurationMinutes} min)");
                });

                if (exam.ExamVenue != null)
                {
                    column.Item().Text(text =>
                    {
                        text.Span("Venue: ").SemiBold();
                        text.Span($"{exam.ExamVenue.VenueName} - {exam.ExamVenue.Location}");
                    });
                }
            });
        }

        private static void ComposeContent(IContainer container, List<ExamEnrollment> enrollments)
        {
            container.Column(column =>
            {
                column.Spacing(14);

                var groups = enrollments
                    .GroupBy(e => e.ExamRoom?.RoomName ?? "Unassigned")
                    .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

                foreach (var group in groups)
                {
                    column.Item().Element(section => ComposeRoomSection(section, group.Key, group
                        .OrderBy(e => e.SeatNumber, StringComparer.OrdinalIgnoreCase)
                        .ToList()));
                }
            });
        }

        private static void ComposeRoomSection(IContainer container, string roomName, List<ExamEnrollment> enrollments)
        {
            container.Column(column =>
            {
                column.Item().BorderBottom(1).BorderColor(Colors.Blue.Darken2).PaddingBottom(2)
                    .Text(roomName).FontSize(13).Bold().FontColor(Colors.Blue.Darken2);

                column.Item().PaddingTop(6).Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(4);
                        columns.RelativeColumn(2);
                    });

                    table.Header(header =>
                    {
                        header.Cell().Element(HeaderCell).Text("Seat Number");
                        header.Cell().Element(HeaderCell).Text("Candidate Name");
                        header.Cell().Element(HeaderCell).Text("Application ID");
                    });

                    foreach (var enrollment in enrollments)
                    {
                        table.Cell().Element(BodyCell).Text(enrollment.SeatNumber ?? "-");
                        table.Cell().Element(BodyCell).Text(enrollment.JobApplication?.CandidateName ?? "-");
                        table.Cell().Element(BodyCell).Text(enrollment.JobApplicationId.ToString());
                    }
                });
            });
        }

        private static IContainer HeaderCell(IContainer container) =>
            container.DefaultTextStyle(x => x.SemiBold().FontSize(9)).PaddingBottom(3).BorderBottom(1).BorderColor(Colors.Grey.Lighten1);

        private static IContainer BodyCell(IContainer container) =>
            container.PaddingVertical(3).DefaultTextStyle(x => x.FontSize(9));
    }
}
